apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: database-ondemand
spec:
  weight: 100
  template:
    metadata:
      labels:
        workload-tier: database
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      taints:
        - key: tier
          value: database
          effect: NoSchedule
        - key: capacity
          value: ondemand
          effect: NoSchedule
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: topology.kubernetes.io/zone
          operator: In
          values:
{{ toYaml .Values.karpenter.zones | indent 12 }}
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
