apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: frontend-spot
spec:
  weight: 20
  template:
    metadata:
      labels:
        workload-tier: frontend
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      taints:
        - key: tier
          value: frontend
          effect: NoSchedule
        - key: capacity
          value: spot
          effect: NoSchedule
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: topology.kubernetes.io/zone
          operator: In
          values:
{{ toYaml .Values.karpenter.zones | indent 12 }}
  disruption:
    budgets:
      - nodes: "10%"
        reasons: ["Underutilized", "Empty"]
      - nodes: "1"
        reasons: ["Drifted"]
        schedule: "0 22 * * 1-5"
        duration: "8h"
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
