apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: KubleOps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/firassBenNacib/KubleOps-manifest.git
    targetRevision: HEAD   
    path: manifest              
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
  # namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
