apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubleops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/firassBenNacib/KubleOps-manifest.git
    targetRevision: HEAD   
    path: manifest              
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: argo.syncWaves.enabled
          value: "false" 
  destination:
    server: https://kubernetes.default.svc
  # namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas