{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-backend
  namespace: {{ .Values.backend.namespace }}
  labels:
    app: backend
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    {{- if .Values.argo.syncWaves.enabled }}argocd.argoproj.io/sync-wave: "{{ .Values.argo.syncWaves.networkPolicies }}"{{- end }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}