apiVersion: v1
data:
  root-password: RXhlbXBsZVBhc3M=
  user-password: RXhlbXBsZVBhc3M=
  username: RXhlbXBsZUFkbWlu
kind: Secret
type: Opaque
metadata:
  name: mysql-secret
  namespace: database
  labels:
    app: mysql
    app.kubernetes.io/name: {{ .Values.mysql.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    {{- if .Values.argo.syncWaves.enabled }}argocd.argoproj.io/sync-wave: "{{ .Values.argo.syncWaves.config }}"{{- end }}