apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: RXhlbXBsZVBhc3M=      
  MYSQL_DATABASE: VmFjY2luYXRpb25BcHA=        
  MYSQL_USER: RXhlbXBsZUFkbWlu                
  MYSQL_PASSWORD: RXhlbXBsZVBhc3M=             
kind: Secret
type: Opaque
metadata:
  name: mysql-secret
  namespace: database
  labels:
    app: mysql
    app.kubernetes.io/name: {{ .Values.mysql.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    {{- if .Values.argo.syncWaves.enabled }}argocd.argoproj.io/sync-wave: "{{ .Values.argo.syncWaves.config }}"{{- end }}