apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.mysql.namespace }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - port: {{ .Values.mysql.containerPort }}
      targetPort: {{ .Values.mysql.containerPort }}
  type: ClusterIP
