apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
  namespace: frontend
data:
  env.js: |
    (function(window) {
      window["env"] = window["env"] || {};
      window["env"]["baseUrl"] = "http://api.devops.firasbennacib.com/springMVC";
    })(this);
