apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: {{ .Values.frontend.namespace }}
  labels:
    app: frontend
    app.kubernetes.io/name: {{ .Values.frontend.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    {{- if .Values.argo.syncWaves.enabled }}argocd.argoproj.io/sync-wave: "{{ .Values.argo.syncWaves.config }}"{{- end }}
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;
      root /usr/share/nginx/html;

      location / {
        try_files $uri $uri/ /index.html;
      }
    }
