{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-allow-list
  namespace: {{ .Values.mysql.namespace }}
  labels:
    app: mysql
    app.kubernetes.io/name: {{ .Values.mysql.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    {{- if .Values.argo.syncWaves.enabled }}argocd.argoproj.io/sync-wave: "{{ .Values.argo.syncWaves.networkPolicies }}"{{- end }}
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.backend.namespace }}
          podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: {{ .Values.mysql.containerPort }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.dnsNamespace }}
          podSelector:
            matchLabels:
              {{ .Values.networkPolicy.dnsPodLabelKey }}: {{ .Values.networkPolicy.dnsPodLabelValue }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- if .Values.networkPolicy.linkLocalDnsCidrs }}
    - to:
{{- range $cidr := .Values.networkPolicy.linkLocalDnsCidrs }}
        - ipBlock:
            cidr: {{ $cidr | quote }}
{{- end }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
{{- if .Values.networkPolicy.clusterDnsServiceCidrs }}
    - to:
{{- range $cidr := .Values.networkPolicy.clusterDnsServiceCidrs }}
        - ipBlock:
            cidr: {{ $cidr | quote }}
{{- end }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 465
        - protocol: TCP
          port: 587
{{- end }}
