apiVersion: v1
data:
  SPRING_DATASOURCE_PASSWORD: RXhlbXBsZVBhc3M=
  SPRING_DATASOURCE_USERNAME: RXhlbXBsZUFkbWlu
kind: Secret
type: Opaque
metadata:
  name: db-credentials
  namespace: backend
  labels:
    app: backend
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    {{- if .Values.argo.syncWaves.enabled }}argocd.argoproj.io/sync-wave: "{{ .Values.argo.syncWaves.config }}"{{- end }}